## These pair of functions can be used to cache the inverse of a matrix so 
## that it does not need to be calculated repeatedly, but rather can be 
## retrieved from the cache

## This function generates a "matrix" which is actually a list of 4 functions 
## These functions include:
## set - Stores the matrix values
## get - returns the matrix values
## setinverse - stores the inverse of the matrix
## getinverse - returns the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
      x <<- y
      m <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) m <<- inverse
    getinverse <- function() m
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
  
}


## This function takes a "matrix" generated by the makeCacheMatrix function and
## returns the inverse of the matrix data. It does this by returning the cached
## values if it exists, otherwise it calculates the inverse of the matrix, 
## stores these values and returns them

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data)
  x$setinverse(m)
  m
}
